import type { Platform, SafetyTier } from "./types";

export interface StaticCategory {
  id: string;
  name: string;
  description: string;
  safety: SafetyTier;
  tradeoff: string;
  platforms: Platform[];
  toolRequirement?: string;
  /** Standard paths with ~ notation (not resolved — for display). */
  paths: string[];
  /** Human-readable cleanup command(s). */
  cleanupCommands: string[];
}

function all(...p: Platform[]): Platform[] { return p; }

export const STATIC_CATEGORIES: StaticCategory[] = [
  {
    id: "trash",
    name: "Trash",
    description: "Files you have moved to Trash / Recycle Bin.",
    safety: "safe",
    tradeoff: "Items in the Trash are permanently deleted and cannot be restored.",
    platforms: all("macos", "linux", "windows", "android"),
    paths: ["~/.Trash", "~/.local/share/Trash"],
    cleanupCommands: [
      "macOS: Right-click Trash → Empty Trash",
      "Linux: rm -rf ~/.local/share/Trash/*",
      "Windows: Right-click Recycle Bin → Empty",
    ],
  },
  {
    id: "system-caches",
    name: "System Caches & Logs",
    description: "Assorted removable application caches in your home directory.",
    safety: "safe",
    tradeoff: "Apps rebuild caches automatically as you use them.",
    platforms: all("macos", "linux", "android"),
    paths: ["~/Library/Caches/*", "~/.cache", "~/.termux/cache"],
    cleanupCommands: [
      "macOS: rm -rf ~/Library/Caches/<app-name>",
      "Linux: rm -rf ~/.cache/<app-name>",
    ],
  },
  {
    id: "homebrew-cache",
    name: "Homebrew",
    description: "Downloaded bottle archive cache plus old package versions.",
    safety: "safe",
    tradeoff: "The next brew install re-downloads bottles; brew cleanup keeps current installs.",
    platforms: all("macos", "linux"),
    toolRequirement: "brew",
    paths: ["~/Library/Caches/Homebrew", "~/.cache/Homebrew"],
    cleanupCommands: ["rm -rf ~/Library/Caches/Homebrew", "brew cleanup --prune=all"],
  },
  {
    id: "npm-cache",
    name: "npm Cache",
    description: "Downloaded package tarballs and registry metadata used by npm install.",
    safety: "safe",
    tradeoff: "The next npm install in each project re-downloads packages.",
    platforms: all("macos", "linux", "windows", "android", "ios"),
    toolRequirement: "npm",
    paths: ["~/.npm", "~/AppData/Local/npm-cache"],
    cleanupCommands: ["npm cache clean --force"],
  },
  {
    id: "pnpm-cache",
    name: "pnpm Store",
    description: "Cached package store and metadata used by pnpm.",
    safety: "safe",
    tradeoff: "Packages are re-downloaded on the next pnpm install.",
    platforms: all("macos", "linux", "windows", "android"),
    toolRequirement: "pnpm",
    paths: ["~/.cache/pnpm", "~/AppData/Local/pnpm"],
    cleanupCommands: ["pnpm store prune", "rm -rf ~/.cache/pnpm"],
  },
  {
    id: "yarn-cache",
    name: "Yarn Cache",
    description: "Cached packages used by yarn install.",
    safety: "safe",
    tradeoff: "Packages are re-downloaded on the next yarn install.",
    platforms: all("macos", "linux", "windows", "android"),
    toolRequirement: "yarn",
    paths: ["~/Library/Caches/yarn", "~/.cache/yarn", "~/AppData/Local/Yarn/Cache"],
    cleanupCommands: ["yarn cache clean"],
  },
  {
    id: "pip-cache",
    name: "pip Cache",
    description: "Cached Python package wheels used by pip install.",
    safety: "safe",
    tradeoff: "Python packages are re-downloaded on the next pip install.",
    platforms: all("macos", "linux", "windows", "android", "ios"),
    toolRequirement: "pip3",
    paths: ["~/Library/Caches/pip", "~/.cache/pip", "~/AppData/Local/pip/Cache"],
    cleanupCommands: ["pip3 cache purge"],
  },
  {
    id: "cocoapods-cache",
    name: "CocoaPods Cache",
    description: "Downloaded CocoaPods spec and pod archives.",
    safety: "safe",
    tradeoff: "Pods are re-downloaded on the next pod install.",
    platforms: ["macos"],
    toolRequirement: "pod",
    paths: ["~/Library/Caches/CocoaPods"],
    cleanupCommands: ["rm -rf ~/Library/Caches/CocoaPods"],
  },
  {
    id: "flutter-pub-cache",
    name: "Dart / Flutter Pub Cache",
    description: "Downloaded Dart packages used by pub get.",
    safety: "safe",
    tradeoff: "Packages are re-downloaded on the next pub get / flutter run.",
    platforms: all("macos", "linux", "windows", "android"),
    toolRequirement: "flutter",
    paths: ["~/.pub-cache", "~/AppData/Local/Pub/Cache"],
    cleanupCommands: ["rm -rf ~/.pub-cache"],
  },
  {
    id: "flutter-sdk-cache",
    name: "Flutter Engine Cache",
    description: "Pre-built Flutter engine artifacts inside the SDK.",
    safety: "moderate",
    tradeoff: "The next flutter command re-downloads ~1-2 GB of engine artifacts.",
    platforms: all("macos", "linux", "windows", "android"),
    toolRequirement: "flutter",
    paths: ["<flutter-sdk>/bin/cache"],
    cleanupCommands: ["rm -rf $(which flutter)/../cache"],
  },
  {
    id: "xcode-deriveddata",
    name: "Xcode DerivedData",
    description: "Build products, indexes and logs created by Xcode for every project you open.",
    safety: "safe",
    tradeoff: "Your first build after cleaning will be slower while Xcode regenerates everything.",
    platforms: ["macos"],
    toolRequirement: "xcodebuild",
    paths: ["~/Library/Developer/Xcode/DerivedData", "~/Library/Caches/com.apple.dt.Xcode"],
    cleanupCommands: ["rm -rf ~/Library/Developer/Xcode/DerivedData", "rm -rf ~/Library/Caches/com.apple.dt.Xcode"],
  },
  {
    id: "xcode-devicesupport",
    name: "Old iOS DeviceSupport",
    description: "Debug symbols for past iOS versions on devices you have plugged in.",
    safety: "moderate",
    tradeoff: "Debugging an old iOS device may need you to re-plug it once to rebuild symbols.",
    platforms: ["macos"],
    toolRequirement: "xcodebuild",
    paths: ["~/Library/Developer/Xcode/iOS DeviceSupport/*"],
    cleanupCommands: ["cd ~/Library/Developer/Xcode/iOS DeviceSupport && ls -dt */ | tail -n +2 | xargs rm -rf"],
  },
  {
    id: "xcode-simulator-caches",
    name: "Simulator Caches",
    description: "iOS Simulator dyld and app caches.",
    safety: "safe",
    tradeoff: "Simulators take slightly longer to launch once.",
    platforms: ["macos"],
    toolRequirement: "xcrun",
    paths: ["~/Library/Developer/CoreSimulator/Caches"],
    cleanupCommands: ["rm -rf ~/Library/Developer/CoreSimulator/Caches"],
  },
  {
    id: "ios-simulators",
    name: "Unused iOS Simulators",
    description: "Simulator devices Xcode no longer uses but keeps on disk.",
    safety: "moderate",
    tradeoff: "You may need to re-create a simulator if you switch iOS versions.",
    platforms: ["macos"],
    toolRequirement: "xcrun",
    paths: ["~/Library/Developer/CoreSimulator/Devices/<unused-udids>"],
    cleanupCommands: ["xcrun simctl delete unavailable"],
  },
  {
    id: "gradle-build-caches",
    name: "Gradle Build Caches",
    description: "Compiled module and dependency caches shared across Android/JVM builds.",
    safety: "safe",
    tradeoff: "The first build after cleaning is slower while dependencies reload.",
    platforms: all("macos", "linux", "windows", "android"),
    paths: ["~/.gradle/caches"],
    cleanupCommands: ["rm -rf ~/.gradle/caches"],
  },
  {
    id: "gradle-wrapper-dists",
    name: "Gradle Wrapper Downloads",
    description: "Downloaded Gradle distributions used by ./gradlew.",
    safety: "safe",
    tradeoff: "The next ./gradlew run re-downloads the bundled Gradle version.",
    platforms: all("macos", "linux", "windows", "android"),
    paths: ["~/.gradle/wrapper/dists"],
    cleanupCommands: ["rm -rf ~/.gradle/wrapper/dists"],
  },
  {
    id: "docker",
    name: "Docker",
    description: "Unused images, stopped containers, build cache and local volumes.",
    safety: "advanced",
    tradeoff: "Containers and images are removed and must be re-pulled or rebuilt later.",
    platforms: all("macos", "linux", "windows"),
    toolRequirement: "docker",
    paths: [],
    cleanupCommands: ["docker system prune -af --volumes"],
  },
  {
    id: "go-build-cache",
    name: "Go Build Cache",
    description: "Compiled Go package artifacts and downloaded module sources.",
    safety: "safe",
    tradeoff: "The first go build after cleaning is slower.",
    platforms: all("macos", "linux", "windows", "android"),
    toolRequirement: "go",
    paths: ["~/.cache/go-build", "~/Library/Caches/go-build", "~/go/pkg/mod"],
    cleanupCommands: ["go clean -cache", "go clean -modcache"],
  },
  {
    id: "cargo-registry-cache",
    name: "Cargo Registry Cache",
    description: "Downloaded crate archives used by cargo build.",
    safety: "safe",
    tradeoff: "Crates are re-downloaded on the next cargo build.",
    platforms: all("macos", "linux", "windows", "android"),
    toolRequirement: "cargo",
    paths: ["~/.cargo/registry/cache"],
    cleanupCommands: ["rm -rf ~/.cargo/registry/cache"],
  },
  {
    id: "dotnet-nuget",
    name: ".NET / NuGet",
    description: "Downloaded NuGet packages and HTTP caches used by dotnet restore.",
    safety: "moderate",
    tradeoff: "The next dotnet restore re-downloads packages, which can be slow.",
    platforms: all("macos", "linux", "windows"),
    toolRequirement: "dotnet",
    paths: ["~/.nuget/packages", "~/.local/share/NuGet/v3-cache", "/tmp/NuGetScratch"],
    cleanupCommands: ["dotnet nuget locals all --clear"],
  },
  {
    id: "chocolatey-cache",
    name: "Chocolatey Cache",
    description: "HTTP download cache kept by Chocolatey package installs.",
    safety: "safe",
    tradeoff: "Packages are re-downloaded on the next choco install.",
    platforms: ["windows"],
    toolRequirement: "choco",
    paths: ["%TEMP%\\chocolatey"],
    cleanupCommands: ["choco cache remove"],
  },
  {
    id: "scoop-cache",
    name: "Scoop Cache",
    description: "Downloaded installers kept by Scoop for app updates.",
    safety: "safe",
    tradeoff: "Apps re-download installers on the next scoop update.",
    platforms: ["windows"],
    toolRequirement: "scoop",
    paths: ["%USERPROFILE%\\scoop\\cache"],
    cleanupCommands: ["scoop cache rm *"],
  },
];

/** Returns static categories applicable to the given platform. */
export function staticCategoriesForPlatform(platform: Platform): StaticCategory[] {
  return STATIC_CATEGORIES.filter((c) => c.platforms.includes(platform));
}
